##
## EPITECH PROJECT, 2023
## repo_name
## File description:
## Makefile
##

all:
		@make -C ./my_string
		@make -C ./my_stdlib
		@make -C ./my_printf

clean:
		@make -C ./my_string clean
		@make -C ./my_stdlib clean
		@make -C ./my_printf clean

fclean:	clean
		@make -C ./my_string fclean
		@make -C ./my_stdlib fclean
		@make -C ./my_printf fclean

re:	fclean all
